language: ruby
rvm:
  - 2.5.0
install:
  - bundle
  - npm install
before_script:
  - psql -c 'create database pgapp_development;' -U postgres
  - psql -c 'create database pgapp_test;' -U postgres
  - rails db:migrate
script:
  - rspec
  - rubocop
