language: ruby
rvm:
  - 2.5.1
install:
  - bundle install
  - npm install
before_script:
  - psql -c 'create database pgapp_development; create database pgapp_development;' -U postgres
  - rails db:migrate
script:
  - rspec
